apiVersion: v1
kind: Service
metadata:
  name: sonarq-service
  labels:
    app: sonarq-deployment
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: sonarq-deployment
  type: LoadBalancer